version: '3.7'

services:
  mysql:
    image: mysql:8.1.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hikari_pool_party
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

  prometheus:
      image: prom/prometheus
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "9090:9090"
      volumes:
        - /Users/vbozovic/usavrsavanje/HikariPoolParty/HikariPlayground/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'