spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      keepalive-time: 0
      max-lifetime: 1800000
      minimum-idle: 25
      maximum-pool-size: 25

server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"
