main:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    name: mainDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      keepalive-time: 0
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 1

database:
  metadata:
    introspect: aircrafts_data,airports_data,boarding_passes,bookings,flights,seats,ticket_flights,tickets

server:
  port: 8083
management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
